apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
    app: lamp
type: Opaque
data:
  ##all below values are base64 encoded
  ##rootpw is root
  ##user is user
  ##password is mypwd
  rootpw: cm9vdAo=
  user: dXNlcgo=
  password: bXlwd2QK
