apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max-demo-lr
  namespace: quotas
spec:
  limits:
  - max:
      cpu: "300m"
      memory: "500Mi"
    min:
      cpu: "150m"
      memory: "250Mi"
    type: Container
