apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    app: lns
spec:
  containers:
  - name: liveness
    image: nginx:latest
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
         port: 80
#      httpGet:
#        path: /
#        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: livenesshttp-svc
spec:
  selector:
    app: lns
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

