apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    app: lns
spec:
  containers:
  - name: liveness
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /liveness; sleep 6000
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command:
        - cat
        - /liveness123
      initialDelaySeconds: 5
      periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: liveness-svc
spec:
  selector:
    app: lns
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

