apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
     color: green 

---
apiVersion: v1
kind: Service
metadata:
  name: mypod-svc
spec:
        #  type: LoadBalancer 
  selector: 
     app: myapp
  ports:
  - port: 80

