apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
spec:
  volumes:
    - name: myvol
      persistentVolumeClaim:
       claimName: dynamic-claim
  containers:
    - name: con1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: myvol


