apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: quotas
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    count/pods: "10"
    count/deployments.apps: "2"
    count/services: "3"
    count/secrets: "3"
    count/replicasets.apps: "3"
    count/configmaps: "5"
